export let categories = [
  { id: 0, topic: "askreddit" },
  { id: 1, topic: "worldnews" },
  { id: 2, topic: "videos" },
  { id: 3, topic: "funny" },
  { id: 4, topic: "todayilearned" },
  { id: 5, topic: "pics" },
  { id: 6, topic: "gaming" },
  { id: 7, topic: "news" },
  { id: 8, topic: "gifs" },
  { id: 9, topic: "aww" },
  { id: 10, topic: "showerthoughts" },
  { id: 11, topic: "science" },
  { id: 12, topic: "politics" },
  { id: 13, topic: "nba" },
  { id: 14, topic: "warriors" },
  { id: 15, topic: "warriors" },
  { id: 16, topic: "warriors" },
  { id: 17, topic: "warriors" },
  { id: 18, topic: "warriors" },
];
